# ragkit/desktop/main.py
"""RAGKIT Desktop backend — Étape 12 : finalisation."""

from __future__ import annotations

import argparse
import asyncio
import hmac
import logging
import re
import sys
import uuid
import uvicorn
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from logging.handlers import RotatingFileHandler
from starlette.middleware.base import BaseHTTPMiddleware

# Add project root to sys.path to allow absolute imports when run as a script
import os
project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from ragkit.desktop.settings_store import ensure_storage_dirs, get_log_dir  # noqa: E402

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Log sanitization
# ---------------------------------------------------------------------------

_SENSITIVE_PATTERNS = [
    (re.compile(r"(sk-|pk_|AKIA|ghp_|gho_|glpat-|xoxb-|xoxp-)[A-Za-z0-9_\-]{10,}"), "[REDACTED_KEY]"),
    (re.compile(r"(password|secret|token|api_key)=\S+", re.IGNORECASE), r"\1=[REDACTED]"),
    (re.compile(r"Bearer\s+[A-Za-z0-9._\-]+"), "Bearer [REDACTED]"),
]


class SanitizedFormatter(logging.Formatter):
    """Logging formatter that redacts sensitive tokens from log messages."""

    def format(self, record: logging.LogRecord) -> str:
        msg = super().format(record)
        for pattern, replacement in _SENSITIVE_PATTERNS:
            msg = pattern.sub(replacement, msg)
        return msg


def setup_logging() -> None:
    # Ensure directories are created before configuring logging
    ensure_storage_dirs()

    log_file = get_log_dir() / "ragkit-backend.log"
    file_handler = RotatingFileHandler(
        log_file, maxBytes=10 * 1024 * 1024, backupCount=5, encoding="utf-8"
    )
    formatter = SanitizedFormatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
    file_handler.setFormatter(formatter)

    stream_handler = logging.StreamHandler(sys.stdout)
    stream_handler.setFormatter(formatter)

    logging.basicConfig(
        level=logging.INFO,
        handlers=[file_handler, stream_handler],
    )

APP_NAME = "LOKO"
VERSION = "1.4.39"

# ---------------------------------------------------------------------------
# Backend authentication middleware
# ---------------------------------------------------------------------------

# Paths that do NOT require the backend token (health check used by watchdog)
_PUBLIC_PATHS = {"/health"}


class BackendTokenMiddleware(BaseHTTPMiddleware):
    """Reject requests that do not carry a valid X-Backend-Token header.

    The token is a UUID v4 generated by the Tauri shell at startup and passed
    to the Python backend via ``--secret``.  This prevents any other local
    process from calling the API.
    """

    def __init__(self, app: FastAPI, *, secret: str) -> None:
        super().__init__(app)
        self._secret = secret

    async def dispatch(self, request: Request, call_next):  # type: ignore[override]
        if request.url.path in _PUBLIC_PATHS:
            return await call_next(request)

        token = request.headers.get("X-Backend-Token", "")
        if not hmac.compare_digest(token, self._secret):
            return JSONResponse(status_code=401, content={"detail": "Unauthorized"})

        return await call_next(request)


# ---------------------------------------------------------------------------
# Security headers middleware
# ---------------------------------------------------------------------------

class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):  # type: ignore[override]
        response = await call_next(request)
        response.headers["X-Content-Type-Options"] = "nosniff"
        response.headers["X-Frame-Options"] = "DENY"
        response.headers["Cache-Control"] = "no-store"
        response.headers["X-Request-Id"] = str(uuid.uuid4())
        return response


# ---------------------------------------------------------------------------
# App factory
# ---------------------------------------------------------------------------

def create_app(*, backend_secret: str = "") -> FastAPI:
    app = FastAPI(title="RAGKIT Desktop API", version=VERSION)

    # --- Security middlewares (outermost first) ---
    if backend_secret:
        app.add_middleware(BackendTokenMiddleware, secret=backend_secret)

    app.add_middleware(SecurityHeadersMiddleware)

    app.add_middleware(
        CORSMiddleware,
        allow_origins=["http://localhost:1420", "https://tauri.localhost", "http://tauri.localhost"],
        allow_credentials=True,
        allow_methods=["GET", "POST", "PUT", "DELETE", "OPTIONS"],
        allow_headers=["Content-Type", "X-Backend-Token"],
    )

    from ragkit.desktop.api import wizard, ingestion, sources, chunking, embedding, vector_store, retrieval, rerank, llm, chat, agents, monitoring, security, general
    from ragkit.desktop.ingestion_runtime import runtime

    app.include_router(wizard.router)
    app.include_router(sources.router)
    app.include_router(ingestion.router)
    app.include_router(ingestion.settings_router)
    app.include_router(chunking.router)
    app.include_router(embedding.router)
    app.include_router(vector_store.router)
    app.include_router(retrieval.router)
    app.include_router(rerank.router)
    app.include_router(llm.router)
    app.include_router(agents.router)
    app.include_router(chat.router)
    app.include_router(monitoring.router)
    app.include_router(security.router)
    app.include_router(general.router)

    @app.on_event("startup")
    async def _start_background_tasks():
        _install_windows_error_handler()
        # Initialize conversations DB and migrate existing JSON files
        from ragkit.desktop.conversation_db import get_conversation_db
        db = get_conversation_db()
        db.migrate_json_files()
        runtime.ensure_background_tasks()
        from ragkit.desktop.sync_scheduler import sync_scheduler
        await sync_scheduler.start()

    @app.on_event("shutdown")
    async def _stop_background_tasks():
        from ragkit.desktop.sync_scheduler import sync_scheduler
        await sync_scheduler.stop()

    @app.get("/health")
    async def health_check():
        return {"ok": True, "version": VERSION}

    @app.post("/shutdown")
    async def shutdown():
        logger.info("Shutdown requested")
        asyncio.get_event_loop().call_later(0.5, lambda: sys.exit(0))
        return {"ok": True}

    return app


def _install_windows_error_handler() -> None:
    """Suppress ConnectionResetError on Windows ProactorEventLoop.

    Windows raises WinError 10054 when a client disconnects abruptly (e.g.
    Tauri health-check probes).  Without this handler the unhandled exception
    crashes the entire uvicorn server.
    """
    if sys.platform != "win32":
        return

    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        loop = asyncio.get_event_loop()
    original_handler = loop.get_exception_handler()

    def _handler(loop: asyncio.AbstractEventLoop, context: dict) -> None:
        exception = context.get("exception")
        if isinstance(exception, ConnectionResetError):
            logger.debug("Suppressed ConnectionResetError: %s", exception)
            return
        if original_handler:
            original_handler(loop, context)
        else:
            loop.default_exception_handler(context)

    loop.set_exception_handler(_handler)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--port", type=int, default=8100)
    parser.add_argument("--secret", type=str, default="")
    args = parser.parse_args()

    setup_logging()

    if not args.secret:
        logger.warning("No --secret provided; backend token authentication is DISABLED")

    app = create_app(backend_secret=args.secret)
    logger.info(f"Starting RAGKIT backend on port {args.port}")
    uvicorn.run(
        app,
        host="127.0.0.1",
        port=args.port,
        log_level="info",
        timeout_keep_alive=30,
    )


if __name__ == "__main__":
    main()
