# ragkit/desktop/main.py
"""RAGKIT backend — supports both desktop (Tauri) and server (Docker/VPS) modes."""

from __future__ import annotations

import argparse
import asyncio
import contextvars
import hmac
import logging
import re
import sys
import uuid
import uvicorn
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from logging.handlers import RotatingFileHandler
from starlette.middleware.base import BaseHTTPMiddleware

# Context variable for request ID correlation across all loggers
request_id_var: contextvars.ContextVar[str] = contextvars.ContextVar("request_id", default="-")

# Add project root to sys.path to allow absolute imports when run as a script
import os
project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

# Load .env file if python-dotenv is available
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

from ragkit.desktop.settings_store import ensure_storage_dirs, get_log_dir  # noqa: E402

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Log sanitization
# ---------------------------------------------------------------------------

_SENSITIVE_PATTERNS = [
    (re.compile(r"(sk-|pk_|AKIA|ghp_|gho_|glpat-|xoxb-|xoxp-)[A-Za-z0-9_\-]{10,}"), "[REDACTED_KEY]"),
    (re.compile(r"(password|secret|token|api_key)=\S+", re.IGNORECASE), r"\1=[REDACTED]"),
    (re.compile(r"Bearer\s+[A-Za-z0-9._\-]+"), "Bearer [REDACTED]"),
]


class SanitizedFormatter(logging.Formatter):
    """Logging formatter that redacts sensitive tokens and includes request ID."""

    def format(self, record: logging.LogRecord) -> str:
        record.request_id = request_id_var.get("-")
        msg = super().format(record)
        for pattern, replacement in _SENSITIVE_PATTERNS:
            msg = pattern.sub(replacement, msg)
        return msg


def setup_logging() -> None:
    # Ensure directories are created before configuring logging
    ensure_storage_dirs()

    log_file = get_log_dir() / "ragkit-backend.log"
    file_handler = RotatingFileHandler(
        log_file, maxBytes=10 * 1024 * 1024, backupCount=5, encoding="utf-8"
    )
    formatter = SanitizedFormatter("%(asctime)s - %(name)s - %(levelname)s - [%(request_id)s] %(message)s")
    file_handler.setFormatter(formatter)

    stream_handler = logging.StreamHandler(sys.stdout)
    stream_handler.setFormatter(formatter)

    logging.basicConfig(
        level=logging.INFO,
        handlers=[file_handler, stream_handler],
    )

APP_NAME = "LOKO"
VERSION = "1.4.48"

# ---------------------------------------------------------------------------
# Backend authentication middleware (desktop mode — Tauri token)
# ---------------------------------------------------------------------------

# Paths that do NOT require authentication
_PUBLIC_PATHS = {"/health"}
_SERVER_ADMIN_PREFIX = "/api/admin"
_LEGACY_API_PREFIX = "/api"


class BackendTokenMiddleware(BaseHTTPMiddleware):
    """Reject requests that do not carry a valid X-Backend-Token header.

    The token is a UUID v4 generated by the Tauri shell at startup and passed
    to the Python backend via ``--secret``.  This prevents any other local
    process from calling the API.
    """

    def __init__(self, app: FastAPI, *, secret: str) -> None:
        super().__init__(app)
        self._secret = secret

    async def dispatch(self, request: Request, call_next):  # type: ignore[override]
        if request.url.path in _PUBLIC_PATHS:
            return await call_next(request)

        token = request.headers.get("X-Backend-Token", "")
        if not hmac.compare_digest(token, self._secret):
            return JSONResponse(status_code=401, content={"detail": "Unauthorized"})

        return await call_next(request)


class ServerAdminPrefixMiddleware(BaseHTTPMiddleware):
    """Expose server administration under /api/admin while preserving /api."""

    async def dispatch(self, request: Request, call_next):  # type: ignore[override]
        path = request.scope.get("path", "")
        if path == _SERVER_ADMIN_PREFIX:
            new_path = _LEGACY_API_PREFIX
        elif isinstance(path, str) and path.startswith(f"{_SERVER_ADMIN_PREFIX}/"):
            new_path = f"{_LEGACY_API_PREFIX}{path[len(_SERVER_ADMIN_PREFIX):]}"
        else:
            return await call_next(request)

        request.scope["path"] = new_path
        raw_path = request.scope.get("raw_path")
        if isinstance(raw_path, bytes):
            request.scope["raw_path"] = new_path.encode("utf-8")
        return await call_next(request)


# ---------------------------------------------------------------------------
# Security headers middleware
# ---------------------------------------------------------------------------

class SecurityHeadersMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):  # type: ignore[override]
        rid = str(uuid.uuid4())
        request_id_var.set(rid)
        request.state.request_id = rid
        response = await call_next(request)
        response.headers["X-Content-Type-Options"] = "nosniff"
        response.headers["X-Frame-Options"] = "DENY"
        response.headers["Cache-Control"] = "no-store"
        response.headers["X-Request-Id"] = rid
        return response


# ---------------------------------------------------------------------------
# App factory
# ---------------------------------------------------------------------------

def _get_mode() -> str:
    """Return the running mode: 'desktop' or 'server'."""
    return os.environ.get("RAGKIT_MODE", "desktop")


def create_app(*, backend_secret: str = "", mode: str | None = None) -> FastAPI:
    run_mode = mode or _get_mode()
    is_server = run_mode == "server"

    title = "RAGKIT Server API" if is_server else "RAGKIT Desktop API"
    app = FastAPI(title=title, version=VERSION)

    # --- Security middlewares (outermost first) ---
    if is_server:
        from ragkit.desktop.middleware.api_key_auth import ApiKeyMiddleware
        app.add_middleware(ApiKeyMiddleware)
        app.add_middleware(ServerAdminPrefixMiddleware)
    elif backend_secret:
        app.add_middleware(BackendTokenMiddleware, secret=backend_secret)

    app.add_middleware(SecurityHeadersMiddleware)

    # --- CORS ---
    if is_server:
        cors_env = os.environ.get("RAGKIT_CORS_ORIGINS", "")
        origins = [o.strip() for o in cors_env.split(",") if o.strip()]
        if not origins:
            logger.warning(
                "RAGKIT_CORS_ORIGINS is not set; no cross-origin requests will be allowed. "
                "Set RAGKIT_CORS_ORIGINS to a comma-separated list of allowed origins."
            )
        elif "*" in origins:
            logger.warning("RAGKIT_CORS_ORIGINS is set to '*'; all origins are allowed — restrict this in production")
    else:
        origins = ["http://localhost:1420", "https://tauri.localhost", "http://tauri.localhost"]

    allowed_headers = ["Content-Type", "X-Backend-Token", "X-API-Key", "Authorization"]
    app.add_middleware(
        CORSMiddleware,
        allow_origins=origins,
        allow_credentials=True,
        allow_methods=["GET", "POST", "PUT", "DELETE", "OPTIONS"],
        allow_headers=allowed_headers,
    )

    # --- Rate limiting (server mode) ---
    if is_server:
        try:
            from slowapi import Limiter, _rate_limit_exceeded_handler
            from slowapi.util import get_remote_address
            from slowapi.errors import RateLimitExceeded

            limiter = Limiter(
                key_func=get_remote_address,
                default_limits=["60/minute"],
                storage_uri="memory://",
            )
            app.state.limiter = limiter
            app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)
            logger.info("Rate limiting enabled (60/min default)")
        except ImportError:
            logger.warning("slowapi not installed; rate limiting is disabled")

    # --- Routers ---
    from ragkit.desktop.api import wizard, ingestion, sources, chunking, embedding, vector_store, retrieval, rerank, llm, chat, agents, monitoring, security, general
    from ragkit.desktop.ingestion_runtime import runtime

    app.include_router(wizard.router)
    app.include_router(sources.router)
    app.include_router(ingestion.router)
    app.include_router(ingestion.settings_router)
    app.include_router(chunking.router)
    app.include_router(embedding.router)
    app.include_router(vector_store.router)
    app.include_router(retrieval.router)
    app.include_router(rerank.router)
    app.include_router(llm.router)
    app.include_router(agents.router)
    app.include_router(chat.router)
    app.include_router(monitoring.router)
    app.include_router(security.router)
    app.include_router(general.router)

    # --- Public chat API (server mode) ---
    if is_server:
        from ragkit.desktop.api.public_chat import router as public_chat_router
        app.include_router(public_chat_router)

    @app.on_event("startup")
    async def _start_background_tasks():
        _install_windows_error_handler()
        # Initialize conversations DB and migrate existing JSON files
        from ragkit.desktop.conversation_db import get_conversation_db
        db = get_conversation_db()
        db.migrate_json_files()
        runtime.ensure_background_tasks()
        from ragkit.desktop.sync_scheduler import sync_scheduler
        await sync_scheduler.start()

    @app.on_event("shutdown")
    async def _stop_background_tasks():
        from ragkit.desktop.sync_scheduler import sync_scheduler
        await sync_scheduler.stop()

    @app.get("/health")
    async def health_check():
        return {"ok": True, "version": VERSION, "mode": run_mode}

    # /shutdown is only available in desktop mode (dangerous on VPS)
    if not is_server:
        @app.post("/shutdown")
        async def shutdown():
            logger.info("Shutdown requested")
            asyncio.get_event_loop().call_later(0.5, lambda: sys.exit(0))
            return {"ok": True}

    # --- Static file serving (server mode) ---
    if is_server:
        _mount_static_files(app)

    return app


def _mount_static_files(app: FastAPI) -> None:
    """Serve the React frontend build as static files with SPA fallback."""
    from pathlib import Path
    from fastapi.staticfiles import StaticFiles
    from fastapi.responses import FileResponse

    # Look for static files in several possible locations
    candidates = [
        Path(__file__).resolve().parent.parent.parent / "static",  # /app/static in Docker
        Path.cwd() / "static",
    ]
    static_dir = None
    for candidate in candidates:
        if candidate.is_dir() and (candidate / "index.html").exists():
            static_dir = candidate
            break

    if static_dir is None:
        logger.warning("No static frontend build found; UI will not be available")
        return

    logger.info("Serving frontend from %s", static_dir)

    # SPA fallback: serve index.html for non-API, non-file routes
    @app.middleware("http")
    async def _spa_fallback(request: Request, call_next):
        response = await call_next(request)
        path = request.url.path
        # If the route was not found and it's not an API call, serve index.html
        if (
            response.status_code == 404
            and not path.startswith("/api")
            and not path.startswith("/health")
            and "." not in path.split("/")[-1]
        ):
            return FileResponse(str(static_dir / "index.html"))
        return response

    app.mount("/", StaticFiles(directory=str(static_dir), html=True), name="static")


def _install_windows_error_handler() -> None:
    """Suppress ConnectionResetError on Windows ProactorEventLoop.

    Windows raises WinError 10054 when a client disconnects abruptly (e.g.
    Tauri health-check probes).  Without this handler the unhandled exception
    crashes the entire uvicorn server.
    """
    if sys.platform != "win32":
        return

    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        loop = asyncio.get_event_loop()
    original_handler = loop.get_exception_handler()

    def _handler(loop: asyncio.AbstractEventLoop, context: dict) -> None:
        exception = context.get("exception")
        if isinstance(exception, ConnectionResetError):
            logger.debug("Suppressed ConnectionResetError: %s", exception)
            return
        if original_handler:
            original_handler(loop, context)
        else:
            loop.default_exception_handler(context)

    loop.set_exception_handler(_handler)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--port", type=int, default=8100)
    parser.add_argument("--secret", type=str, default="")
    parser.add_argument("--mode", type=str, choices=["desktop", "server"], default=None)
    parser.add_argument("--host", type=str, default=None)
    args = parser.parse_args()

    # --mode flag overrides env var
    if args.mode:
        os.environ["RAGKIT_MODE"] = args.mode

    run_mode = _get_mode()

    setup_logging()

    if run_mode == "desktop" and not args.secret:
        logger.warning("No --secret provided; backend token authentication is DISABLED")

    app = create_app(backend_secret=args.secret, mode=run_mode)

    host = args.host or ("0.0.0.0" if run_mode == "server" else "127.0.0.1")
    logger.info("Starting RAGKIT backend [%s mode] on %s:%d", run_mode, host, args.port)
    uvicorn.run(
        app,
        host=host,
        port=args.port,
        log_level="info",
        timeout_keep_alive=30,
    )


if __name__ == "__main__":
    main()
