import { invoke } from "@tauri-apps/api/core";

interface HealthCheckResponse {
  ok: boolean;
  version?: string;
}

export const ipc = {
  healthCheck: () => invoke<HealthCheckResponse>("health_check"),
  getEmbeddingConfig: () => invoke("get_embedding_config"),
  updateEmbeddingConfig: (config: any) => invoke("update_embedding_config", { config }),
  testEmbeddingConnection: (provider?: string, model?: string) => invoke("test_embedding_connection", { provider, model }),
  getVectorStoreConfig: () => invoke("get_vector_store_config"),
  updateVectorStoreConfig: (config: any) => invoke("update_vector_store_config", { config }),
  startIngestion: (incremental = false) => invoke("start_ingestion", { incremental }),
  getIngestionStatus: () => invoke("get_ingestion_status"),
  getSemanticSearchConfig: () => invoke("get_semantic_search_config"),
  updateSemanticSearchConfig: (config: any) => invoke("update_semantic_search_config", { config }),
  resetSemanticSearchConfig: () => invoke("reset_semantic_search_config"),
  runSemanticSearch: (payload: any) => invoke("run_semantic_search_with_options", { payload }),
  getLexicalSearchConfig: () => invoke("get_lexical_search_config"),
  updateLexicalSearchConfig: (config: any) => invoke("update_lexical_search_config", { config }),
  resetLexicalSearchConfig: () => invoke("reset_lexical_search_config"),
  runLexicalSearch: (query: any) => invoke("lexical_search", { query }),
  getBM25IndexStats: () => invoke("get_bm25_index_stats"),
  rebuildBM25Index: () => invoke("rebuild_bm25_index"),
  getHybridSearchConfig: () => invoke("get_hybrid_search_config"),
  updateHybridSearchConfig: (config: any) => invoke("update_hybrid_search_config", { config }),
  resetHybridSearchConfig: () => invoke("reset_hybrid_search_config"),
  runUnifiedSearch: (query: any) => invoke("unified_search", { query }),
  getRerankConfig: () => invoke("get_rerank_config"),
  updateRerankConfig: (config: any) => invoke("update_rerank_config", { config }),
  resetRerankConfig: () => invoke("reset_rerank_config"),
  testRerankConnection: () => invoke("test_rerank_connection"),
  testRerank: (query: any) => invoke("test_rerank", { query }),
  getRerankModels: (provider: string) => invoke("get_rerank_models", { provider }),
  getLLMConfig: () => invoke("get_llm_config"),
  updateLLMConfig: (config: any) => invoke("update_llm_config", { config }),
  resetLLMConfig: () => invoke("reset_llm_config"),
  testLLMConnection: () => invoke("test_llm_connection"),
  getLLMModels: (provider: string) => invoke("get_llm_models", { provider }),
  getAgentsConfig: () => invoke("get_agents_config"),
  updateAgentsConfig: (config: any) => invoke("update_agents_config", { config }),
  resetAgentsConfig: () => invoke("reset_agents_config"),
  runChat: (query: any) => invoke("chat", { query }),
  startChatStream: (query: any) => invoke("chat_stream", { query }),
  stopChatStream: () => invoke("chat_stream_stop"),
  startOrchestratedChat: (query: any) => invoke("chat_orchestrated", { query }),
  newConversation: () => invoke("new_conversation"),
  getConversationHistory: () => invoke("get_conversation_history"),
};
